steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/valiant-store-407920/samplecditest:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/valiant-store-407920/samplecditest:$SHORT_SHA']
  

